

class I18N:
    def __init__(self, lang):
        if lang == "en":
            self.load_text_in_english()
        elif lang == "tr":
            self.load_text_in_turkish()
        else:
            raise NotImplementedError("Unsupported language.")

    def load_text_in_english(self):
        self.title = "Film Catalogue (English)"
        self.bAdmin = "Admin"
        self.bGuest = "Guest"
        self.bLanguage = "Language"
        self.lblUsername = "Username:"
        self.lblPassword = "Password:"
        self.bLogin = "Login"
        self.bRegister = "Register"
        self.bHomePage = "Home Page"
        self.bPrevious = "Previous Page"
        self.bAdd = "Add Movies"
        self.bRemove = "Remove Movies"
        self.bFilter = "Filter Movies"
        self.bSearch = "Search Movies"
        self.bRandom = "Random Movie Recommendation"
        self.trtitle = "Turkish Title:"
        self.entitle = "English Title:"
        self.trdesc = "Turkish Description:"
        self.endesc = "English Description:"
        self.AddDir = "Add Director"
        self.AddAct = "Add Actor"
        self.lblyear = "Year:"
        self.txtyear = "Year"
        self.bSave = "Save"
        self.dName = "Director Name:"
        self.dNames = "Director Name"
        self.dAdd = "Add Director"
        self.dtitle = "Add Director Page"
        self.sImage = "Select Image"
        self.deletetitle = "Delete Film Page"
        self.chooseDirector = "Choose Director"
        self.cDirector = "--Choose Director--"
        self.cActor = "--Choose Actor/Actress--"
        self.bFilter = "Filter"
        self.stitle = "Search Movie"
        self.Error1 = "Error!"
        self.Error2 = "Error :"
        self.problem1 = "Please be sure that you fill every empty blank!"
        self.problem2 = "Please be sure that you typed more than two letters"
        self.problem3 = "Already have this account"
        self.done1 = "Done"
        self.done2 = "Register Successful!"
        self.done3 = "Director added successfully."
        self.warning1 = "Warning"
        self.warning2 = "There is not an account with this username"
        self.warning3 = "Wrong Password"
        self.mtitle = "Name of Movie"
        self.cpassword ="Show Password"
        self.pAdd1 = "Please fill the Turkish title."
        self.pAdd2 = "Please fill the English title."
        self.pAdd3 = "Please fill the Turkish description."
        self.pAdd4 = "Please fill the English description."
        self.pAdd5 = "Please select one or more category for movie."
        self.pAdd6 = "Please select director."
        self.pAdd7 = "Please add actor/actress."
        self.pAdd8 = "Please fill the imdb point."
        self.pAdd9 = "Please fill the year."
        self.pAdd10 = "Please upload image for movie."
        self.msave = "Movie saved."


    def load_text_in_turkish(self):
        self.title = "Film Catalogue (Türkçe)"
        self.bAdmin = "Yönetici"
        self.bGuest = "Misafir"
        self.bLanguage = "Dil"
        self.lblUsername = "Kullanıcı Adı:"
        self.lblPassword = "Şifre:"
        self.bLogin = "Giriş"
        self.bRegister = "Kayıt Ol"
        self.bHomePage = "Ana Sayfa"
        self.bPrevious = "Önceki Sayfa"
        self.bAdd = "Film Ekle"
        self.bRemove = "Film Sil"
        self.bFilter = "Filmleri Filtrele"
        self.bSearch = "Filmleri Ara"
        self.bRandom = "Rastgele Film Önerisi"
        self.trtitle = "Türkçe Başlık:"
        self.entitle = "İngilizce Başlık:"
        self.trdesc = "Türkçe Konu:"
        self.endesc = "İngilizce Konu:"
        self.AddDir = "Yönetmen Ekle"
        self.AddAct = "Aktör Ekle"
        self.lblyear = "Yıl:"
        self.txtyear = "Yıl"
        self.bSave = "Kaydet"
        self.dName = "Yönetmen Adı:"
        self.dNames = "Yönetmen Adı"
        self.dAdd = "Yönetmeni Ekle"
        self.dtitle = "Yönetmen Ekleme Sayfası"
        self.sImage = "Resim Seç"
        self.deletetitle = "Film Silme Sayfası"
        self.chooseDirector = "Yönetmen Seç"
        self.cDirector = "--Yönetmen Seç--"
        self.cActor = "--Oyuncu Seç--"
        self.bFilter = "Filtre"
        self.stitle = "Film Arama"
        self.Error1 = "Hata!"
        self.Error2 = "Hata :"
        self.problem1 = "Lütfen her şeyi doldurduğunuzdan emin olun!"
        self.problem2 = "Lütfen ikiden fazla harf yazdığınızdan emin olun"
        self.problem3 = "Böyle bir hesap halihazırda var"
        self.done1 = "Kabul"
        self.done2 = "Kayıt Başarılı!"
        self.done3 = "Yönetmen başarıyla kaydedildi."
        self.warning1 = "Uyarı"
        self.warning2 = "Bu kullanıcı adına sahip bir hesap yok"
        self.warning3 = "Hatalı Şifre"
        self.mtitle = "Filmin Adı"
        self.cpassword = "Parolayı Göster"
        self.pAdd1 = "Lütfen Türkçe başlığı doldurunuz."
        self.pAdd2 = "Lütfen İngilizce başlığı doldurunuz."
        self.pAdd3 = "Lütfen Türkçe konuyu doldurunuz."
        self.pAdd4 = "Lütfen İngilizce konuyu doldurunuz."
        self.pAdd5 = "Lütfen film için bir veya daha fazla kategori seçin."
        self.pAdd6 = "Lütfen yönetmen seçin."
        self.pAdd7 = "Lütfen oyuncu ekleyin."
        self.pAdd8 = "Lütfen imdb puanını doldurunuz."
        self.pAdd9 = "Lütfen yılı doldurunuz."
        self.pAdd10 = "Lütfen film için resim yükleyin."
        self.msave = "Film kaydedildi."

